baseurl = "https://tiffanychi.me/"
languageCode = "en"
title = ""
enableRobotsTXT = true
disable404 = false
googleAnalytics = "G-1RCB9NJFMG"

[params]
  author = "Tiffany Chi"
  description = "Personal blog for Tiffany Pyke"
  font = "https://fonts.googleapis.com/css?family=Open+Sans:300,600"
