baseurl = "https://momentum-birth.com/"
languageCode = "en"
title = ""
enableRobotsTXT = true
disable404 = false
googleAnalytics = "G-1RCB9NJFMG"

[params]
  author = "Tiffany Pyke"
  description = "Personal blog for Tiffany Pyke"
  font = "https://fonts.googleapis.com/css?family=Open+Sans:300,600"
